# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
