# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 11:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import docs.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('can_access', models.CharField(choices=[('ALL', 'All'), ('ONLY ME', 'Only Me'), ('STAFF', 'Staff'), ('ADMIN', 'Admin')], default='ALL', max_length=20)),
                ('owner', models.ForeignKey(on_delete=models.SET(docs.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
