# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import docs.models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='slug',
            field=models.SlugField(default=docs.models.uuid_url64, max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(),
        ),
    ]
